### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by wgtmac** [apache/parquet-site#54]
I added a new download page for 1.14.0 release: https://github.com/apache/parquet-site/commit/6ad835f9e9f37763cf032cb079474255e492d1ea.

The build and deploy failed: https://github.com/apache/parquet-site/actions/runs/8995459641/job/24710455486. 

Do you know how to fix this? @vinooganesh

**Comment by wgtmac** [comment]
I think this is an issue introduced by Hugo v0.125.0: https://github.com/cue-lang/cue/issues/3053#issuecomment-2070137474

**Comment by vinooganesh** [comment]
Yeah that seems like a Hugo issue. I'll drop the Hugo version later tonight and see if that fixes it.
