### ISSUE TITLE
Automate site generation

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-site#64]
We moved our site source to [github](https://github.com/apache/parquet-site). It is much better than svn but still not working as it should. Currently, we have to generate the site manually before checking in. It would be much better if the site generation would be automatic so we can simply accept PRs on the source files.
 One option to achieve this is the [Pelican CMS System](https://blog.getpelican.com/) as described at [.asf.yaml features for git repositories](https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories#id-.asf.yamlfeaturesforgitrepositories-StaticwebsitecontentgenerationviaPelicanCMS). Not sure if this is the best solution though. Another solution might be to trigger a jenkins build for the changes on master and after generating the site with middleman commit the files to the branch asf-site. 

**Reporter**: [Gabor Szadovszky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gszadovszky) / @gszadovszky
#### Related issues:
- [Switch to git for website](https://github.com/apache/parquet-java/issues/2377) (is related to)

<sub>**Note**: *This issue was originally created as [PARQUET-1686](https://issues.apache.org/jira/browse/PARQUET-1686). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Uwe Korn](https://issues.apache.org/jira/browse/PARQUET-1686?#comment-16963045) / @xhochy:
In Arrow we are using Jekyll with Github Actions to automatically deploy our site: <https://github.com/apache/arrow-site/blob/master/.github/workflows/deploy.yml>

**Comment by alamb** [comment]
I believe this issue is complete now given the conversion to Hugo by @vinooganesh

**Comment by alamb** [comment]
FYI @julienledem

**Comment by julienledem** [comment]
Thank you for the ping
